# Site settings
title: CloudSkin
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: #"/CloudSkin" # the subpath of your site, e.g. /blog/
url: #"sergial273.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
